### ISSUE TITLE
multi-face keyoint detection 

### ISSUE THREAD

**Issue by soans1994** [wutayng/2d-pose-estimation-tf-keras#3]
hello author,

Does this repo has multi-face keyoint detection support?
I want to ask wheter the COCO person dataset is specialized for multi-person?
i have trained a simple model using FCN for face keypoint regression. Can you please tell me how we can get heatmaps of muliple faces in the bottom-up approach. My current model takes input of 96x96x1 image and gives 96x96x15 size heatmaps for 15 keypoints. I trained my model using kaggle datset consisting of images with single face pre cropped to 96x96. Do i need the dataset with multiple faces? and do I need bouding box information or mask information too?

Please give me your advice
thank you

**Comment by wutayng** [comment]
This model is trained on the COCO Multi-Person Dataset, so yes it support multi-person keypoint detection. This is for body pose - not face keypoints.

If you want your model to predict multiples, the dataset must contain multiples. You can learn more about the data structure here: https://github.com/wutayng/2d-pose-estimation-tf-keras/blob/master/notebooks/02-2DPose-UNet-heatmap.ipynb

**Comment by soans1994** [comment]
@wutayng  thank you man

**Comment by soans1994** [comment]
while training coco dataset,
If i crop the image and pass it to training, it will be same as single person detection right?
I shd use the whole image 3 times with different labels while training if there are 3 persons right?
